# ======================================
# kvstore database configuration
# ======================================


# --- Network Settings ---
# The port the database will listen on.
port=6379

# The IP address to bind to.
# Use 127.0.0.1 for local secure access (recommended)
bind=127.0.0.1

# --- Memory limits ---
# The maximum number of keys allowed in the database before eviction starts.
max_number_keys=1000000

# --- Persistence ---
# File path for the Append-Only File (AOF).
aof_path=db.aof